In [1]:
#Passo a passo do projeto
#pip install pandas openpyxl nbformat ipykerkel plotly

#Passo 1 Abrir a bae de dados (importar a base de dados)
import pandas as pd

tabela = pd.read_csv("clientes_treino_churn.csv")
display(tabela)

#Passo 2 Visualizar a base de dados e julgar o que e util/inutil
tabela = tabela.drop(columns= "ID_Cliente" )
display(tabela)

,ID_Cliente,Idade,Sexo,Tempo_Como_Cliente_Meses,Frequencia_Uso,Ligacoes_Callcenter,Dias_Atraso,Assinatura,Duracao_Contrato,Total_Gasto,Meses_Ultima_Interacao,Cancelou
0,TR00001,23,Masculino,20,20,1,23,Basic,Quarterly,290.32,2,0
1,TR00002,60,Feminino,70,25,6,16,Standard,Quarterly,955.61,23,0
2,TR00003,20,Feminino,6,15,8,22,Basic,Annual,187.36,14,1
3,TR00004,50,Feminino,25,15,12,6,Standard,Monthly,533.86,9,1
4,TR00005,44,Feminino,42,24,9,6,Basic,Quarterly,397.61,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,TR00996,56,Masculino,51,6,10,24,Standard,Monthly,750.72,21,1
996,TR00997,63,Feminino,67,32,12,23,Standard,Annual,886.80,24,1
997,TR00998,56,Feminino,64,27,5,27,Premium,Quarterly,1272.62,15,1
998,TR00999,18,Feminino,17,30,8,1,Standard,Annual,544.71,5,1
999,TR01000,41,Masculino,47,31,8,12,Premium,Quarterly,1128.60,1,0

,Idade,Sexo,Tempo_Como_Cliente_Meses,Frequencia_Uso,Ligacoes_Callcenter,Dias_Atraso,Assinatura,Duracao_Contrato,Total_Gasto,Meses_Ultima_Interacao,Cancelou
0,23,Masculino,20,20,1,23,Basic,Quarterly,290.32,2,0
1,60,Feminino,70,25,6,16,Standard,Quarterly,955.61,23,0
2,20,Feminino,6,15,8,22,Basic,Annual,187.36,14,1
3,50,Feminino,25,15,12,6,Standard,Monthly,533.86,9,1
4,44,Feminino,42,24,9,6,Basic,Quarterly,397.61,5,0
...,...,...,...,...,...,...,...,...,...,...,...
995,56,Masculino,51,6,10,24,Standard,Monthly,750.72,21,1
996,63,Feminino,67,32,12,23,Standard,Annual,886.80,24,1
997,56,Feminino,64,27,5,27,Premium,Quarterly,1272.62,15,1
998,18,Feminino,17,30,8,1,Standard,Annual,544.71,5,1
999,41,Masculino,47,31,8,12,Premium,Quarterly,1128.60,1,0

In [2]:
#Passo 3: Corrigir o problemas da base de dados(tratamento de dados)
display(tabela.info())
#Nesse caso não temos problemas com a nossa base de dados, então não sera necessarios esse passo. Mas se precisar, usaria o seguinte 

tabela = tabela.dropna()
display(tabela.info())

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Idade                     1000 non-null   int64
 1   Sexo                      1000 non-null   str
 2   Tempo_Como_Cliente_Meses  1000 non-null   int64
 3   Frequencia_Uso            1000 non-null   int64
 4   Ligacoes_Callcenter       1000 non-null   int64
 5   Dias_Atraso               1000 non-null   int64
 6   Assinatura                1000 non-null   str
 7   Duracao_Contrato          1000 non-null   str
 8   Total_Gasto               1000 non-null   float64
 9   Meses_Ultima_Interacao    1000 non-null   int64
 10  Cancelou                  1000 non-null   int64
dtypes: float64(1), int64(7), str(3)
memory usage: 86.1 KB

None

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Idade                     1000 non-null   int64
 1   Sexo                      1000 non-null   str
 2   Tempo_Como_Cliente_Meses  1000 non-null   int64
 3   Frequencia_Uso            1000 non-null   int64
 4   Ligacoes_Callcenter       1000 non-null   int64
 5   Dias_Atraso               1000 non-null   int64
 6   Assinatura                1000 non-null   str
 7   Duracao_Contrato          1000 non-null   str
 8   Total_Gasto               1000 non-null   float64
 9   Meses_Ultima_Interacao    1000 non-null   int64
 10  Cancelou                  1000 non-null   int64
dtypes: float64(1), int64(7), str(3)
memory usage: 86.1 KB

None

In [3]:
#Passo 4: Analise inicial (entender quantos clientes cancelaram)

#Quantidade - Quantos caras são "0" e quantos são "1" na coluna que cancelou
display(tabela["Cancelou"].value_counts())

#Porcentagem
#display(tabela["Cancelou"].value_counts(normalize=True))
display(tabela["Cancelou"].value_counts(normalize=True).map("{:.1%}".format))

Cancelou
1    587
0    413
Name: count, dtype: int64

Cancelou
1    58.7%
0    41.3%
Name: proportion, dtype: str

In [4]:
#Passo 5: Analise detalhada (causa do cancelamento dos clientes, como cada coluna impacta na cancelamento da assinatura)
import plotly.express as px 
print(tabela.columns)
for coluna in tabela.columns:
    grafico = px.histogram(tabela, x=coluna, color="Cancelou", text_auto=True)
    grafico.show()

Index(['Idade', 'Sexo', 'Tempo_Como_Cliente_Meses', 'Frequencia_Uso',
       'Ligacoes_Callcenter', 'Dias_Atraso', 'Assinatura', 'Duracao_Contrato',
       'Total_Gasto', 'Meses_Ultima_Interacao', 'Cancelou'],
      dtype='str')

In [5]:
#Passo 6: Como resolver os cancelamentos ?

#Podemos analisar que 58.7% dos clientes cancelaram  a assinatura, algo esta errado

#Assinaturas por mês são as mais canceladas - Podemos tentar fazer uma promoçao para incentivar o cliente a mudar o seu plano.
condicao = tabela["Duracao_Contrato"] != "Monthly"
tabela = tabela[condicao]

#Apos 8/9 dias de atraso o indice de cancelamento aumentou
condicao = tabela["Dias_Atraso"] <= 8
tabela = tabela[condicao]

#Apos 2 ligacoes o indice de cancelamentou aumentou, na 9 ligacao o indice de cancelamentou chegou no seu apice 
condicao = tabela["Ligacoes_Callcenter"] <= 2
tabela = tabela[condicao]


display(tabela["Cancelou"].value_counts(normalize=True).map("{:.1%}".format))

#Resolvendo esses 3 problemas saimos de 58% para 26%

Cancelou
0    73.9%
1    26.1%
Name: proportion, dtype: str